# Site settings
title: lmromero.com
email: luismiguel@lmromero.com.com
description: "Mi web personal construida con jekyll."
baseurl: ""
url: "http://localhost:4000"
twitter_username: yosoyluismi23
github_username:  lmromero

# Build settings
markdown: kramdown
permalink: pretty
