# Site settings
title: Luis Miguel Romero
email: lmromeromadejon@gmail.com
description: "Mi web personal construida con jekyll."
baseurl: ""
url: "http://localhost:4000"
twitter_username: yosoyluismi
github_username:  lmromero

# Build settings
markdown: kramdown
permalink: pretty
